title: More to Explore
description: MtE wiki and Downloads!
site_favicon: favicon.ico
encoding: UTF-8
show_downloads: false
lsi: false
safe: true
source: [main]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: pages-themes/minimal@v0.2.0
plugins:
 - "jekyll-sitemap"
